### PR TITLE
Update forgot pass

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by mjhea0** [comment]
https://assembly.com/runbook/bounties/320

**Comment by madflojo** [comment]
So I'm good with requiring folks to enter the old pass to change it. But I'm thinking in a reset scenario we may need an alternative form that doesn't require the old pass but requires the reset URL to be true. What do you think?

**Comment by mjhea0** [comment]
@madflojo I'll have the reset pass/email auth done by the weekend. Sound good?

**Comment by madflojo** [comment]
@mjhea0, That would be awesome actually! So are you thinking a different form for a reset pass?

**Comment by mjhea0** [comment]
@madflojo yeah. IMO there should be both - 

1. Password change
1. Password reset (to retrieve a new password when the user forgets his/her password)

Thoughts?

**Comment by madflojo** [comment]
Yup makes sense to me

**Pull request merged**
