### PR TITLE
Redesign static site

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by mjhea0** [comment]
https://assembly.com/runbook/bounties/322

**Comment by madflojo** [comment]
Looked at this last night I like the new header bar and the black on the bottom. Did notice an alignment issue once logged in though, you mind checking that out?

**Comment by mjhea0** [comment]
Alignment issue? I don't see that.

**Comment by madflojo** [comment]
Yeah you have to login, navigate to another page and then you'll see it.

screen shot 2015-06-22 at 6 42 45 pm

**Comment by mjhea0** [comment]
@madflojo updated

**Pull request merged**
