### PR TITLE
updates to docker setup, adding docker machine and compose

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by madflojo** [comment]
Hey @mjhea0,

Noticed the dockerfiles 404'ing too huh? I'm going through and updating the ubuntu ones as well and should be merging that here in a few minutes.

**Comment by mjhea0** [comment]
Yes, I'm updating now as well. :)

**Comment by mjhea0** [comment]
ready! :+1:

**Comment by mjhea0** [comment]
https://assembly.com/runbook/bounties/310

**Comment by mjhea0** [comment]
@madflojo How are you setting the config in the docker containers?

**Comment by madflojo** [comment]
@mjhea0 for development environment or for Production and Staging?

**Comment by mjhea0** [comment]
@madflojo development

**Comment by madflojo** [comment]
Nothing fancy really: https://github.com/asm-products/cloudroutes-service/blob/master/src/web/bootstrap.sh#L11-13

In production I'm using salt to generate the config files and having the Dockerfile copy them during build

**Pull request merged**
