### PR TITLE
security update: force a limit to the HTTP GET monitor

### PR DESCRIPTION
**Pull request by noushi**
fixes: DOS and "financial pit" vulnerability in the HTTP GET monitor
in https://assembly.com/runbook/bounties/243

### CODE REVIEW

**Comment by madflojo** [comment]
Hey @noushi, 

Can you include the `http-get-statuscode` and `http-post` monitors as well in this fix. Also have you already been able to test this?

**Comment by noushi** [comment]
I've tested the [modified code](https://github.com/noushi/cloudroutes-service/blob/3380f4730a1c26b4c0f5b48efecb22a8541a82c2/src/monitors/checks/http-keyword/__init__.py#L30-L43) in a standalone script and it works with files less than 2MB and more than 2MB.

Let me check the other monitors and get back to you

**Comment by noushi** [comment]
@madflojo Okay, so I've fixed the http status monitor

But regarding the http post monitor, it doesn't make sense to limit the post payload at the request level.
Such limitation should be done at the monitor form level: we can't accept any payload, and truncate it when sending it. Best case, it won't work well, worst case: the post verb would make the remote web service do something unintended and possibly destructive...

**Comment by madflojo** [comment]
Cool, I will pull it down in a bit and test it out.

**Comment by noushi** [comment]
Great, I'll wait for your update.

**Comment by madflojo** [comment]
tested out well, looks like we can merge it.

**Pull request merged**
