### PR TITLE
added email templates, updated dependencies

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by mjhea0** [comment]
https://assembly.com/runbook/bounties/234

**Comment by mjhea0** [comment]
ready! @madflojo

**Comment by madflojo** [comment]
Templates are good, We should maybe include a link to our twitter account or something.

 For email rather than emailing from flask directly I'd like to use mandrill. 

https://mandrillapp.com/api/docs/messages.JSON.html

You can make it async calls so we don't have to wait for slow SMTP servers.

**Comment by mjhea0** [comment]
This is just a sample template, which can easily be changed. I'll set up the API call to Mandril later today.

**Comment by madflojo** [comment]
Cool, mind adding a link to our twitter page? https://twitter.com/runbookio after that is added I'll merge.

**Comment by mjhea0** [comment]
Do you mind if I use https://github.com/volker48/flask-mandrill since it will simplify passing variables into the email - i.e., `{{ user }}`

**Comment by madflojo** [comment]
Yeah thats fine, I more wanted to make sure we use mandrill. There are a few benefits to mandrill.

1. Don't have to wait for smtp servers
2. Don't have to worry about our servers getting blacklisted and dealing with it later
3. They have a good searchable view of what emails were sent, what was blacklisted/reported spam/bounced.

**Pull request merged**
