### PR TITLE
Bookie integration (Scaffolding helper script)

### PR DESCRIPTION
**Pull request by noushi**
Solves: https://assembly.com/runbook/bounties/197

### CODE REVIEW

**Comment by madflojo** [comment]
I'll probably have some time to check this out tomorrow and will let you know what I think.

**Comment by noushi** [comment]
@madflojo  sure.

**Comment by madflojo** [comment]
@noushi 

So I got a chance to check this out and I dig the end result. I am now a fan of the templates!

Couple of things for this though.

* Can we place this in a different directory than `bin/src`, maybe move these to a directory `devhelpers/bookie` or something.
* Is bookie a fork? Do we really need to have the full package in our repository or can we rather have a doc that folks can follow to install it.
  * If not we should clean up anything that isn't absolutely required.
  * We may also consider a separate repo for this and other "dev helpers"
* We should probably have an index of the fields available in the README.

**Comment by noushi** [comment]
@madflojo 

Great! :-)

. sure, bookie location was bothering me also.

. a fork of what? It's a standalone python `cliff` program. We can do away with just the documentation and keeping it where it is.
    - the original repo is here: http://github.com/noushi/bookie
   - yes, a separate `devhelpers` would be also good

. you're right, I'll add that from the `wtforms` classes docs.

**Comment by madflojo** [comment]
@noushi,

So if its standalone do we need to make install it and include the `.egg` stuff or can we just run it adhoc? If we can remove all of the packaging stuff we might as well put it in this repo in `devhelpers/bookie`.

**Comment by noushi** [comment]
@madflojo

The way I see it, the developer can run a make install from the bookie dir so he can use bookie through his virtualenv install.

An egg is not good enough since there are many improvements I want to add later on.

That said, I could publish the package so a pip install bookie would run just fine.

Bookie source could then be anywhere. 

Which one do you prefer?

Sent from Yahoo Mail on Android

**Comment by madflojo** [comment]
Nah if the `make install` is required than i'm find just moving it to `devhelper/bookie`. For the README though you may want to call out the virtualenv step.

Let me know once you move the directories around and I'll merge.

**Comment by noushi** [comment]
will do.

regarding virtualenv, I don't think it should be a required step, rather a general recommendation for any python dev effort...

**Comment by noushi** [comment]
@madflojo 
I moved bookie in `devhelpers/` and documented install procedure in README.md.
Good to go?

**Comment by madflojo** [comment]
yup looks good

**Comment by noushi** [comment]
@madflojo cool, thanks!

**Pull request merged**
